- params:
    git:
      repoName: fportantier-vulpyNew
      # [Mandatory]
      # List of branches to scan
      branches:
        - master
    scan:
      projects:
            - pathExclusions: # <-- Correctly indented as a child of 'prone'
                - "**/utils*"
                - "**/good*"
                - "**/bad*"
    jfrogPlatform:
      # ... (add JFrog platform details here, or leave as null/empty object)
