- params:
    git:
      repoName: fportantier-vulpyNew
      # [Mandatory]
      # List of branches to scan
      branches:
        - master
    scan:
      includeAllVulnerabilities: true
      projects:
        pathExclusions:
          - "*utils*"
          - "*bad*"
          - "*good*"
          - "**"
    jfrogPlatform:



