- params:
    git:
      repoName: fportantier-vulpyNew
      # [Mandatory]
      # List of branches to scan
      branches:
        - master
    scan:
      includeAllVulnerabilities: true
      workingDirs:
        - "."
      pathExclusions:
        - "**/utils*"
        - "**/good*"
        - "**/bad*"
    jfrogPlatform:



