- params:
    git:
      repoName: fportantier-vulpyNew
      # [Mandatory]
      # List of branches to scan
      branches:
        - master
    scan:
      projects:
        - prone: # <-- This indicates 'prone' is a mapping/object
            pathExclusions: # <-- Correctly indented as a child of 'prone'
              - "**/utils*"
              - "**/good*"
    jfrogPlatform:
      # ... (add JFrog platform details here, or leave as null/empty object)
