- params:
    git:
      repoName: fportantier-vulpyNew
      # [Mandatory]
      # List of branches to scan
      branches:
        - master
    scan:
      projects:
        - prone
          pathExclusions:
            - "**/utils*"
            - "**/good*"
            - "**/bad*"
    jfrogPlatform:
