- params:
    git:
      repoName: fportantier-vulpyNew
      # [Mandatory]
      # List of branches to scan
      branches:
        - master
    scan:
      pathExclusions:
        - "**/utils*"
        - "**/good*"
        - "*bad*"
        - "**/bad*"
    jfrogPlatform: 


